# Generated by Django 4.1.5 on 2023-01-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_sale_price', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_parameter', models.CharField(max_length=40)),
                ('phone', models.ManyToManyField(through='index.ParameterValue', to='index.phone')),
            ],
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.phone'),
        ),
        migrations.AddField(
            model_name='parametervalue',
            name='phone_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.phoneparameter'),
        ),
    ]
