# Generated by Django 4.1.5 on 2023-01-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PhonePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('when_priced', models.DateTimeField(auto_now_add=True)),
                ('is_sale_price', models.BooleanField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.phone')),
            ],
            options={
                'order_with_respect_to': 'model',
            },
        ),
    ]
